### ISSUE TITLE
Confirm that Plugin Updating is Automatic

### ISSUE THREAD

**Issue by maxsu** [mcneel/RhinoCommonTemplatePackage#11]
Hi @piac, @dbelcher 

In @dbelcher's  [Your First Plugin with C#](https://developer.rhino3d.com/guides/rhinocommon/your-first-plugin-windows/#next-steps) guide, it's recommended to reinstall the plugin each time we rename a command (see [L108](https://github.com/mcneel/developer-rhino3d-com/blame/6/_guide_topics/rhinocommon/your-first-plugin-windows.md#L108)).

I'd like to update that line to reflect the current practice, which seems to be:

1. We do need to manually install the plugin on first build + debug run
2. During subsequent debug runs we _don't_ need to reinstall the plugin after renaming commands

Before I do that, I just want to confirm that this is indeed the behavior. If so, which RhinoCommonTemplatePackage commit caused this? Was it caused by a Rhino update?

Thanks!

**Comment by dbelcher** [comment]
AFAIK, 2. is the intended behavior.  I defer to @piac as he might know which commit changed this behavior.

**Comment by piac** [comment]
Hi @maxsu

I am on vacation but decided to answer your questions quickly. This practice is probably a suggestion due to the command registration policy in Rhino, which @golsby knows more about.

In a few words, if your plug-in loads at startup (not recommended), Rhino will inspect the command names and register them every time, provided that the location of the plug-in does not change. If your plug-in is loaded on demand (default), then command names are cached from the previous command loading. Upon loading, they are updated. This means that the old, changed command names will autocomplete at first, but then might not work when later invoked and finally will be refreshed when the plug-in is finally loaded.

Templates won't do anything regarding this behavior. This is behavor derived

**Comment by maxsu** [comment]
Sorry I interrupted your vacation!

I confirmed that the mistake was mine: After running the debug build and loading rhino, I 1) tested that the old command did not work - this loaded the plugin and refreshed the cache, so 2) the new command appeared to work. When I skip the first step, the command is unavailable.

This is relevant to the tutorial - loading the plugin is sufficient. Whether this can (or should) be done from the template is defintiely another issue. Thanks for the info!
